function(load_env_file filepath)
    if(EXISTS ${filepath})
        file(READ ${filepath} contents)
        string(REPLACE "\n" ";" contents "${contents}")

        foreach(line ${contents})
            if(line MATCHES "^[A-Za-z0-9_]+=.*$")
                string(REPLACE "=" ";" line ${line})
                list(GET line 0 key)
                list(GET line 1 value)
                set(ENV{${key}} ${value})
                message(STATUS "Loaded env variable: $ENV{${key}}")
            endif()
        endforeach()
    else()
        message(WARNING "Env file ${filepath} not found.")
    endif()
endfunction()
